In [2]:
import tensorflow as tf

In [10]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4]) #Slicing technique
print(tensor_indexed[1:5+1 ]) #Slicing technique similar to tf.range(2,6) or tf.range(2,5+1)
print(tensor_indexed[1:6:2]) #Slicing technique with steps of 2
#generally we have tensor_indexed[minindex:maxindex+1]
print(tensor_indexed[:4]) #Slicing technique starts at 0 and ends at 4
print(tensor_indexed[3:]) #Slicing technique starts at 0 and ends at the end of the tensor array
print(tensor_indexed[3:-1]) #Slicing technique starts at 3 and goes 1 element less than the end
print(tensor_indexed[3:-2]) #Slicing technique starts at 3 and goes 2 elements less than the end
print(tensor_indexed[3:-4]) #Slicing technique starts at 3 and goes 4 elements less than the end giving error

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66  7], shape=(4,), dtype=int32)
tf.Tensor([ 4  6 66], shape=(3,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)


In [15]:
tensor_two_d = tf.constant( [ [1, 2,  0],
                                               [3, 5, -1],
                                               [1, 5, 6],
                                               [2,3,8] ] )
print(tensor_two_d[ 0:3, 0:2 ]) # Get first three consecutive rows and then the first two consecutive columns of them
print(tensor_two_d[0:3, :]) # Get first three rows and then rest of the columns
print(tensor_two_d[2, :]) # Get the third row and then rest of the columns, no need to put a range in row/column section if you want to grab a single row/column
print(tensor_two_d[2, 0]) # Get the third row and then first column, no need to put a range in row/column section if you want to grab a single row/column
print(tensor_two_d[2, 1:]) # Get the third row and then the second and third columns, no need to put a range in row/column section if you want to grab a single row/column
print(tensor_two_d[:, 0]) # Grab all the rows and the first column for each row
# print(tensor_two_d[, 0])  =>  Error as we haven't specified the row to be selected
print(tensor_two_d[1:3, 0]) # Grab the first two rows and grab the first elements for each row
print(tensor_two_d[..., 1 ])  # ... here means ' : ' => picking up everything

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant( [
                                                [ [1, 2, 0 ],
                                                [3, 5, -1] ],

                                                [ [10, 2, 0 ],
                                                  [1, 0, 2] ],

                                                [ [5, 8, 0 ],
                                                  [2, 7, 0] ],

                                                [ [2, 1, 9 ],
                                                  [4, -3,  32] ]
                                                ] )
print(tensor_three_d[  0, : , : ])  # first dimension, second dimension and third dimension; here he have taken first tensor with all rows and all columns
# Given 2 by 3 Tensor with 4 elements => Shape = (4, 2, 3)
print(tensor_three_d[  0, 0, : ])  # grabs the first tensor and first row with every column for that row
print(tensor_three_d[0, :, -1]) # grabs the first tensor, then all the rows but the last column => print(tensor_three_d[0, :, 2]) where 2 is the last column
print(tensor_three_d[:2, :, 2]) # grabs the first two tensors , all rows but then the third column similar to print(tensor_three_d[:2, ... , 2])
print(tensor_three_d[..., ..., 2])  # grabs all the tensors and all the rows but the third column (last index in this context) elements