In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)   # constant tensor of 0-D
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3]) # 1- D tensor of int
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90.]) # 1- D tensor of of 5 elements, add '.' changes entire data to float32 from int32
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90], dtype=float) # 1- D tensor of of 5 elements, specifying dtype changes entire data to float32 from int32, precision = 32
print(tensor_one_d)
# Use lower precision for memory constraint issues

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90.], dtype=tf.float32) # can not convert the numbers directly to int64 as it has '.'
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [ ]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world!", " hi"]) # List of strings
print(tensor_string)

tf.Tensor([b'hello world!' b' hi'], shape=(2,), dtype=string)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90.], dtype=tf.float32) # can not convert the numbers directly to int64 as it has '.'
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool) # check for values that match the majority returning false for the minority
print(tensor_one_d)
print(casted_tensor_one_d)

In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d) # 2-D tensor with 5 rows and 3 columns

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
[ [1,2,0],
  [3,5,-1] ],

 [ [10,2,0],
   [1,0,2] ],

[ [5,8,0],
  [2,7,0] ],

 [ [2,1,9],
   [4,-3,32] ],
])
print(tensor_three_d) # 3-D Tensor with 4 2-D elements with 2 rows and 3 columns matrix each

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape) # Shape of tensor

(4, 2, 3)


In [ ]:
print(tensor_three_d.ndim) # Returns the dimension of the tensor

3


In [ ]:
tensor_four_d = tf.constant([
[
   [[1,2,0],
   [3,5,-1]],

   [[10,2,0],
   [1,0,2]],

   [[5,8,0],
   [2,7,0]],

   [[2,1,9],
   [4,-3,32] ],
],

[
  [[103,26,0],
  [3,50,-12]],

  [[100,2,0],
  [1,0,23]],

  [[5,28,0],
  [2,3,0]],

  [[22,1,9],
  [44,-320,32] ],
],

[
  [[13,26,0],
  [3,5,-12]],

  [[10,2,0],
  [1,0,23]],

  [[5,8,0],
  [2,73,0]],

  [[2,1,9],
  [4,-30,32] ],
],
])
print(tensor_four_d) # 3 3-D Tensors with each tensor having 2 rows and 3 columns

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
## Convert numpy array to tensors ##

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
) # Identity matrix returned with 3 rows 1 for leading diagonals but 0 elsewhere, order = 3
# num_columns by default is 3
# dtypes can be float16, bool -> True for leading diagonals but False elsewhere
print(eye_tensor)  # can do print(3*eye_tensor) which will return 3 diagonal wise and elsewhere 0

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[3, ],
    dtype=tf.dtypes.float32,
    name=None
)
#batch shape here specifies the number of tensors => Three 3 x 3 matrices with 1s and 0s
print(eye_tensor)  # can do print(3*eye_tensor) which will return 3 diagonal wise and elsewhere 0

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,4 ],
    dtype=tf.dtypes.float32,
    name=None
)
#batch shape here specifies the number of tensors in 4-D setting =>4 Tensors with Three 3 x 3 matrices with 1s and 0s
print(eye_tensor)  # can do print(3*eye_tensor) which will return 3 diagonal wise and elsewhere 0

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 4, 3, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill (
    [3,4], 5, name=None
)
print(fill_tensor) # fill out a matrix of 3 x 5 with the value of 5

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor) # 5 rows and 3 columns

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
ones_tensor = tf.ones(
    [5,3,6],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor) # 5 Tensors with 3 rows and 6 columns

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(5, 3, 6), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor) # (1,3,4) shape tensor of fill_tensor converted to a tensor of ones

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor) # Tensor with 3 rows and 2 columns  with zeros

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
print(tf.shape(tensor_three_d)) # returns a list of the element, shape and type

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [ ]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1],  [2, 2, 2]], [[3, 3, 3],  [4, 4, 4]]])
tf.rank(t) #3
# Output is a 0-D tensor and its value is 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# shape of tensor 't' is [2, 3]
t = tf.constant([ [1, 1, 1],  [5, 5, 5] ])
tf.rank(t)  # 2 as there are two rows => numpy = 2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t = tf.constant( [ [ [1, 1, 1],  [2, 2, 2]], [[3, 3, 3], [4, 4, 4] ] ] )
tf.size(t) # 12 elements or 12 different positions in our tensor so the size is 12

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
t = tf.constant( [  [1, 1, 1],  [2, 2, 2] ],)
tf.size(t, out_type =tf.float32) # 6 elements or 6 different positions in our tensor so the size is 6

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor) # numbers close to zero (mean), returns a matrix, it also uses std dev values

tf.Tensor(
[[ 0.8242551   0.9034537 ]
 [-0.8922721  -0.15535426]
 [-0.09876909  0.02286462]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [1, ],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor) # values ranging from 0-8, max value defaults to 1 if not specified

tf.Tensor([7.908473], shape=(1,), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor) # 5 x 5 (shape) values ranging from minval to maxval

tf.Tensor(
[[577 814 621 910 202]
 [431 930 387  95 892]
 [692 849 692 469 671]
 [ 85 115 504 586 474]
 [606 266 948 395 794]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10)) # changing seed to 1 will output different output

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3, ],maxval=5, dtype=tf.int32,seed=10)) # exact same output even after random seeds fed and selection from uniform distribution curve

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
